apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-duplicate-service-accounts
spec:
  background: false
  validationFailureAction: enforce
  rules:
    - name: validate-unique-service-account
      match:
        any:
          - resources:
              kinds:
                - Deployment
      context:
        - name: serviceAccountsAllDeployments
          apiCall:
            urlPath: "/apis/apps/v1/deployments"
            jmesPath: "items[?@.metadata.ownerReferences == false || metadata.ownerReferences[?uid != '{{ request.object.metadata.keys(@).contains(@, 'ownerReferences') && request.object.metadata.ownerReferences[0].uid }}']].spec.template.spec.serviceAccountName"
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: Equals
            value: CREATE
      validate:
        message: "The service account is already in use by another deployment."
        deny:
          conditions:
            all:
              - key: "{{ request.object.spec.template.spec.serviceAccountName }}"
                operator: AnyIn
                value: "{{ serviceAccountsAllDeployments }}"
